### ISSUE TITLE
canMakePayments() still hangs for Android [purchases_flutter: ^3.4.4]

### ISSUE THREAD

**Issue by kofan** [RevenueCat/purchases-flutter#239]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-flutter/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-flutter/issues)

**Describe the bug**

Even though the bug https://github.com/RevenueCat/purchases-android/issues/348 has been fixed, the method call `await Purchases.canMakePayments()` still hangs in my flutter application for Android. I use the latest `purchases_flutter` version (**`3.4.4`**).

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
[✓] VS Code (version 1.60.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by beylmk** [comment]
Hey @kofan, thanks for bringing this to my attention and sorry for the inconvenience...looks like the latest release didn't pull in the fix. Look out for a hotfix ASAP.

**Comment by kofan** [comment]
Thank you very much, @beylmk!

**Comment by beylmk** [comment]
Hey @kofan, check out 3.4.5...that should contain the fix! If things work for you, would you mind closing out this issue? 

Thanks again for alerting us!

**Comment by kofan** [comment]
Fixed in the release `3.4.5` - thank you!

**Comment by EdesonABizerril** [comment]
Unfortunately I'm still having the same crash issue with version 3.4.5.
I tested it on android 6 and 11. Here's my data:

In Pubspeck file: purchases_flutter: 3.4.5

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.60.1)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.

I would very much like this correction to be done urgently. Thanks!!

**Comment by EdesonABizerril** [comment]
Unfortunately I'm still having the same crash issue with version 3.4.5.
I tested it on android 6 and 11. Here's my data:

In Pubspeck file: purchases_flutter: 3.4.5

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
✗ Unable to find bundled Java version.
[✓] VS Code (version 1.60.1)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.

I would very much like this correction to be done urgently. Thanks!!!

**Comment by vegaro** [comment]
@EdesonABizerril Do you get any crash? Or does canMakePayments just hang without completing? 

Thanks and sorry you're having issues.

**Comment by kofan** [comment]
As for me - I'm not getting a crash (though, I was not getting a crash before as well), and the `canMakePayments()` does not hang anymore after I've updated to `3.4.5`...

**Comment by EdesonABizerril** [comment]
I got confused. This error is similar to the one I'm facing, but it's not exactly this one. Sorry for the confusion. Crash is occurring when I run `Purchases.purchasePackage(package);`.
The sales modal opens but locks completely and the only way to unlock it is by pressing the back button.

**Comment by vegaro** [comment]
Yes please @EdesonABizerril. I will look into it.
